server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sample@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
